biome_types = {
    -1: '(Uncalculated)',
    0: 'Ocean',
    1: 'Plains',
    2: 'Desert',
    3: 'Extreme Hills',
    4: 'Forest',
    5: 'Taiga',
    6: 'Swamppland',
    7: 'River',
    8: 'Hell (Nether)',
    9: 'Sky (End)',
    10: 'Frozen Ocean',
    11: 'Frozen River',
    12: 'Ice Plains',
    13: 'Ice Mountains',
    14: 'Mushroom Island',
    15: 'Mushroom Island Shore',
    16: 'Beach',
    17: 'Desert Hills',
    18: 'Forest Hills',
    19: 'Taiga Hills',
    20: 'Extreme Hills Edge',
    21: 'Jungle',
    22: 'Jungle Hills',
    23: 'Jungle Edge',
    24: 'Deep Ocean',
    25: 'Stone Beach',
    26: 'Cold Beach',
    27: 'Birch Forest',
    28: 'Birch Forest Hills',
    29: 'Roofed Forest',
    30: 'Cold Taiga',
    31: 'Cold Taiga Hills',
    32: 'Mega Taiga',
    33: 'Mega Taiga Hills',
    34: 'Extreme Hills+',
    35: 'Savanna',
    36: 'Savanna Plateau',
    37: 'Messa',
    38: 'Messa Plateau F',
    39: 'Messa Plateau',
    129: 'Sunflower Plains',
    130: 'Desert M',
    131: 'Extreme Hills M',
    132: 'Flower Forest',
    133: 'Taiga M',
    134: 'Swampland M',
    140: 'Ice Plains Spikes',
    141: 'Ice Mountains Spikes',
    149: 'Jungle M',
    151: 'JungleEdge M',
    155: 'Birch Forest M',
    156: 'Birch Forest Hills M',
    157: 'Roofed Forest M',
    158: 'Cold Taiga M',
    160: 'Mega Spruce Taiga',
    161: 'Mega Spruce Taiga 2',
    162: 'Extreme Hills+ M',
    163: 'Savanna M',
    164: 'Savanna Plateau M',
    165: 'Mesa (Bryce)',
    166: 'Mesa Plateau F M',
    167: 'Mesa Plateau M'
}
